version: '3'

services:

  db:
    image: mysql:8.0
    ports:
      - "3307:3306" # change so it will not have conflict with existing one
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=lpv_adb
      - MYSQL_USER=lpv
      - MYSQL_PASSWORD=lpv_dev_pass
      - MYSQL_ROOT_PASSWORD=lpv_dev_root_pass
    volumes:
      - mysql-db-data:/var/lib/mysql
    restart: always

  lpv-adb-be:
    image: lovepetveteriner/lpv-adb-be
    ports:
      - "9991:8080"
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - LPV_MAIL_PASSWORD=${LPV_MAIL_PASSWORD}
      - JDBC_DATABASE_URL=jdbc:mysql://db:3306/lpv_adb
      - JDBC_DATABASE_USERNAME=lpv
      - JDBC_DATABASE_PASSWORD=lpv_dev_pass
    restart: always

  ui:
    image: lovepetveteriner/ui
    ports:
      - "9992:5000"
    expose:
      - "5000"
    # depends_on:
    #   - be
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:9991
    restart: always

  lpv-static-site:
    image: lovepetveteriner/lpv-static-site:latest
    ports:
      - "9993:80"
    expose:
      - "80"
    restart: always

volumes:
  mysql-db-data:
