version: '3'

services:

  # connect db on your local: be sure to have psql client
  # psql --host=localhost --port=5445 --dbname=postgres --username=postgres
  db:
    image: postgres:9.6
    ports:
      - "5445:5432" # change so it will not have conflict with existing psql
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=lpvpass
    volumes:
      - db-data:/var/lib/postgresql/data

  be:
    image: lovepetveteriner/be
    ports:
      - "9991:8080"
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=lpvpass
    restart: always

  ui:
    image: lovepetveteriner/ui
    ports:
      - "9992:5000"
    expose:
      - "5000"
    # depends_on:
    #   - be
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:9991
    restart: always

volumes:
  db-data:
